server:
  port: 81


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.86.195/vue1-0
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher





mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
